### ISSUE TITLE
[build:1ee3febd] Unordered tags: Grating on my OCD :)

### ISSUE THREAD

**Issue by sipickles** [pacedotdev/community#37]
<img width="101" alt="Screenshot 2020-07-04 at 23 18 47" src="https://user-images.githubusercontent.com/8441757/86521765-c9c2cc00-be4c-11ea-8ef9-b4a18d9aec07.png">

Can we get tags organised alphabetically in the side bar? This is totally twisting my melon, man.

**Comment by matryer** [comment]
@sipickles Good point, thanks for pointing this out.

We have fixed this now. Please do a hard reload for the changes to take effect.

**Comment by matryer** [comment]
p.s. this one made it into our blog :) thanks @sipickles https://pace.dev/blog/2020/07/08/pace-july-update-five-new-features.html

**Comment by sipickles** [comment]
Love the blog, thanks!

btw I still see a few instances in old cards. Is that expected?

<img width="106" alt="Screenshot 2020-07-10 at 19 51 16" src="https://user-images.githubusercontent.com/8441757/87188511-dfba0c00-c2e6-11ea-8c25-8093479d2848.png">


build: 3c6f2408
